import unittest


class TestExceptions(unittest.TestCase):
    pass
    # TODO complete exceptions tests


if __name__ == '__main__':
    unittest.main()
